create table agency (id bigint not null, address varchar(255), city varchar(255), name varchar(255), manager_id bigint, primary key (id)) engine=InnoDB;
create table agent (id bigint not null, agency_id bigint not null, primary key (id)) engine=InnoDB;
create table app_user (id bigint not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone_number integer, primary key (id)) engine=InnoDB;
create table car (id bigint not null, is_available bit, license_plate varchar(20), car_description_id bigint not null, primary key (id)) engine=InnoDB;
create table car_description (id bigint not null, brand varchar(255), color varchar(255), img_url varchar(255), max_power integer, max_speed integer, model varchar(255), price_per_day float(53), price_per_hour float(53), seat_number integer, primary key (id)) engine=InnoDB;
create table car_rental (id bigint not null, already_paid float(53), end_date date, is_payment_completed bit, is_with_driver bit, start_date date, status varchar(255) not null, total_price float(53), agent_for_confirmation_id bigint, agent_for_return_id bigint, car_id bigint not null, driver_id bigint, tenant_id bigint not null, primary key (id)) engine=InnoDB;
create table client (r bit not null, id bigint not null, primary key (id)) engine=InnoDB;
create table driver (is_available bit, id bigint not null, primary key (id)) engine=InnoDB;
create table manager (id bigint not null, primary key (id)) engine=InnoDB;
create table payment (id bigint not null, amount float(53), date date, method varchar(255), payment_id bigint not null, primary key (id)) engine=InnoDB;
create table primary_sequence (next_val bigint) engine=InnoDB;
insert into primary_sequence values ( 10000 );
alter table app_user add constraint UK_1j9d9a06i600gd43uu3km82jw unique (email);
alter table agency add constraint FK33tn8fwt9xymoktau7crt8fwl foreign key (manager_id) references manager (id);
alter table agent add constraint FK2karykbqlyw19a0e80gcf9ch9 foreign key (agency_id) references agency (id);
alter table agent add constraint FKn8cpysmp2l0uou3bbfqe9dj4g foreign key (id) references app_user (id);
alter table car add constraint FKo5b90b5fn0asj3e37qmfe1u2v foreign key (car_description_id) references car_description (id);
alter table car_rental add constraint FKl1nefniygdeu8qyvx58gwdvfs foreign key (agent_for_confirmation_id) references agent (id);
alter table car_rental add constraint FK50qmv1pjahvh9n1e9q79jxyfb foreign key (agent_for_return_id) references agent (id);
alter table car_rental add constraint FKgnt9e9ahmdxvk8obxxxcf3pul foreign key (car_id) references car (id);
alter table car_rental add constraint FK3if7anp9a6fium6a9p4nhn6k6 foreign key (driver_id) references driver (id);
alter table car_rental add constraint FKhudwsxpqjnm49dvulqy5hih8f foreign key (tenant_id) references app_user (id);
alter table client add constraint FK2re8ltj5jewc835q5d1id08i9 foreign key (id) references app_user (id);
alter table driver add constraint FKdylhbnatypxmkfua048dq2dkm foreign key (id) references app_user (id);
alter table manager add constraint FKsnqi31uc306jfbm24s0d9rnej foreign key (id) references app_user (id);
alter table payment add constraint FKcgv5h6yy2y2k66bwat9x3ghht foreign key (payment_id) references car_rental (id);
